# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_api_node_v1alpha1_runtime_class import IoK8sApiNodeV1alpha1RuntimeClass  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiNodeV1alpha1RuntimeClass(unittest.TestCase):
    """IoK8sApiNodeV1alpha1RuntimeClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiNodeV1alpha1RuntimeClass(self):
        """Test IoK8sApiNodeV1alpha1RuntimeClass"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_api_node_v1alpha1_runtime_class.IoK8sApiNodeV1alpha1RuntimeClass()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
