# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_api_scheduling_v1_priority_class_list import IoK8sApiSchedulingV1PriorityClassList  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiSchedulingV1PriorityClassList(unittest.TestCase):
    """IoK8sApiSchedulingV1PriorityClassList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiSchedulingV1PriorityClassList(self):
        """Test IoK8sApiSchedulingV1PriorityClassList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_api_scheduling_v1_priority_class_list.IoK8sApiSchedulingV1PriorityClassList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
