# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_apimachinery_pkg_apis_meta_v1_initializer import IoK8sApimachineryPkgApisMetaV1Initializer  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApimachineryPkgApisMetaV1Initializer(unittest.TestCase):
    """IoK8sApimachineryPkgApisMetaV1Initializer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgApisMetaV1Initializer(self):
        """Test IoK8sApimachineryPkgApisMetaV1Initializer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_apimachinery_pkg_apis_meta_v1_initializer.IoK8sApimachineryPkgApisMetaV1Initializer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
