# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_api_authorization_v1beta1_self_subject_access_review_spec import IoK8sApiAuthorizationV1beta1SelfSubjectAccessReviewSpec  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiAuthorizationV1beta1SelfSubjectAccessReviewSpec(unittest.TestCase):
    """IoK8sApiAuthorizationV1beta1SelfSubjectAccessReviewSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiAuthorizationV1beta1SelfSubjectAccessReviewSpec(self):
        """Test IoK8sApiAuthorizationV1beta1SelfSubjectAccessReviewSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_api_authorization_v1beta1_self_subject_access_review_spec.IoK8sApiAuthorizationV1beta1SelfSubjectAccessReviewSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
