# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_api_authentication_v1beta1_user_info import IoK8sApiAuthenticationV1beta1UserInfo  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiAuthenticationV1beta1UserInfo(unittest.TestCase):
    """IoK8sApiAuthenticationV1beta1UserInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiAuthenticationV1beta1UserInfo(self):
        """Test IoK8sApiAuthenticationV1beta1UserInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_api_authentication_v1beta1_user_info.IoK8sApiAuthenticationV1beta1UserInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
