# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_api_batch_v1_job_status import IoK8sApiBatchV1JobStatus  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiBatchV1JobStatus(unittest.TestCase):
    """IoK8sApiBatchV1JobStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiBatchV1JobStatus(self):
        """Test IoK8sApiBatchV1JobStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_api_batch_v1_job_status.IoK8sApiBatchV1JobStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
