# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from api.auditregistration_v1alpha1_api import AuditregistrationV1alpha1Api  # noqa: E501
from argo.rest import ApiException


class TestAuditregistrationV1alpha1Api(unittest.TestCase):
    """AuditregistrationV1alpha1Api unit test stubs"""

    def setUp(self):
        self.api = api.auditregistration_v1alpha1_api.AuditregistrationV1alpha1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_auditregistration_v1alpha1_audit_sink(self):
        """Test case for create_auditregistration_v1alpha1_audit_sink

        """
        pass

    def test_delete_auditregistration_v1alpha1_audit_sink(self):
        """Test case for delete_auditregistration_v1alpha1_audit_sink

        """
        pass

    def test_delete_auditregistration_v1alpha1_collection_audit_sink(self):
        """Test case for delete_auditregistration_v1alpha1_collection_audit_sink

        """
        pass

    def test_get_auditregistration_v1alpha1_api_resources(self):
        """Test case for get_auditregistration_v1alpha1_api_resources

        """
        pass

    def test_list_auditregistration_v1alpha1_audit_sink(self):
        """Test case for list_auditregistration_v1alpha1_audit_sink

        """
        pass

    def test_patch_auditregistration_v1alpha1_audit_sink(self):
        """Test case for patch_auditregistration_v1alpha1_audit_sink

        """
        pass

    def test_read_auditregistration_v1alpha1_audit_sink(self):
        """Test case for read_auditregistration_v1alpha1_audit_sink

        """
        pass

    def test_replace_auditregistration_v1alpha1_audit_sink(self):
        """Test case for replace_auditregistration_v1alpha1_audit_sink

        """
        pass

    def test_watch_auditregistration_v1alpha1_audit_sink(self):
        """Test case for watch_auditregistration_v1alpha1_audit_sink

        """
        pass

    def test_watch_auditregistration_v1alpha1_audit_sink_list(self):
        """Test case for watch_auditregistration_v1alpha1_audit_sink_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
