# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from api.certificates_v1beta1_api import CertificatesV1beta1Api  # noqa: E501
from argo.rest import ApiException


class TestCertificatesV1beta1Api(unittest.TestCase):
    """CertificatesV1beta1Api unit test stubs"""

    def setUp(self):
        self.api = api.certificates_v1beta1_api.CertificatesV1beta1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_certificates_v1beta1_certificate_signing_request(self):
        """Test case for create_certificates_v1beta1_certificate_signing_request

        """
        pass

    def test_delete_certificates_v1beta1_certificate_signing_request(self):
        """Test case for delete_certificates_v1beta1_certificate_signing_request

        """
        pass

    def test_delete_certificates_v1beta1_collection_certificate_signing_request(self):
        """Test case for delete_certificates_v1beta1_collection_certificate_signing_request

        """
        pass

    def test_get_certificates_v1beta1_api_resources(self):
        """Test case for get_certificates_v1beta1_api_resources

        """
        pass

    def test_list_certificates_v1beta1_certificate_signing_request(self):
        """Test case for list_certificates_v1beta1_certificate_signing_request

        """
        pass

    def test_patch_certificates_v1beta1_certificate_signing_request(self):
        """Test case for patch_certificates_v1beta1_certificate_signing_request

        """
        pass

    def test_patch_certificates_v1beta1_certificate_signing_request_status(self):
        """Test case for patch_certificates_v1beta1_certificate_signing_request_status

        """
        pass

    def test_read_certificates_v1beta1_certificate_signing_request(self):
        """Test case for read_certificates_v1beta1_certificate_signing_request

        """
        pass

    def test_read_certificates_v1beta1_certificate_signing_request_status(self):
        """Test case for read_certificates_v1beta1_certificate_signing_request_status

        """
        pass

    def test_replace_certificates_v1beta1_certificate_signing_request(self):
        """Test case for replace_certificates_v1beta1_certificate_signing_request

        """
        pass

    def test_replace_certificates_v1beta1_certificate_signing_request_approval(self):
        """Test case for replace_certificates_v1beta1_certificate_signing_request_approval

        """
        pass

    def test_replace_certificates_v1beta1_certificate_signing_request_status(self):
        """Test case for replace_certificates_v1beta1_certificate_signing_request_status

        """
        pass

    def test_watch_certificates_v1beta1_certificate_signing_request(self):
        """Test case for watch_certificates_v1beta1_certificate_signing_request

        """
        pass

    def test_watch_certificates_v1beta1_certificate_signing_request_list(self):
        """Test case for watch_certificates_v1beta1_certificate_signing_request_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
