# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from api.networking_v1beta1_api import NetworkingV1beta1Api  # noqa: E501
from argo.rest import ApiException


class TestNetworkingV1beta1Api(unittest.TestCase):
    """NetworkingV1beta1Api unit test stubs"""

    def setUp(self):
        self.api = api.networking_v1beta1_api.NetworkingV1beta1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_networking_v1beta1_namespaced_ingress(self):
        """Test case for create_networking_v1beta1_namespaced_ingress

        """
        pass

    def test_delete_networking_v1beta1_collection_namespaced_ingress(self):
        """Test case for delete_networking_v1beta1_collection_namespaced_ingress

        """
        pass

    def test_delete_networking_v1beta1_namespaced_ingress(self):
        """Test case for delete_networking_v1beta1_namespaced_ingress

        """
        pass

    def test_get_networking_v1beta1_api_resources(self):
        """Test case for get_networking_v1beta1_api_resources

        """
        pass

    def test_list_networking_v1beta1_ingress_for_all_namespaces(self):
        """Test case for list_networking_v1beta1_ingress_for_all_namespaces

        """
        pass

    def test_list_networking_v1beta1_namespaced_ingress(self):
        """Test case for list_networking_v1beta1_namespaced_ingress

        """
        pass

    def test_patch_networking_v1beta1_namespaced_ingress(self):
        """Test case for patch_networking_v1beta1_namespaced_ingress

        """
        pass

    def test_patch_networking_v1beta1_namespaced_ingress_status(self):
        """Test case for patch_networking_v1beta1_namespaced_ingress_status

        """
        pass

    def test_read_networking_v1beta1_namespaced_ingress(self):
        """Test case for read_networking_v1beta1_namespaced_ingress

        """
        pass

    def test_read_networking_v1beta1_namespaced_ingress_status(self):
        """Test case for read_networking_v1beta1_namespaced_ingress_status

        """
        pass

    def test_replace_networking_v1beta1_namespaced_ingress(self):
        """Test case for replace_networking_v1beta1_namespaced_ingress

        """
        pass

    def test_replace_networking_v1beta1_namespaced_ingress_status(self):
        """Test case for replace_networking_v1beta1_namespaced_ingress_status

        """
        pass

    def test_watch_networking_v1beta1_ingress_list_for_all_namespaces(self):
        """Test case for watch_networking_v1beta1_ingress_list_for_all_namespaces

        """
        pass

    def test_watch_networking_v1beta1_namespaced_ingress(self):
        """Test case for watch_networking_v1beta1_namespaced_ingress

        """
        pass

    def test_watch_networking_v1beta1_namespaced_ingress_list(self):
        """Test case for watch_networking_v1beta1_namespaced_ingress_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
