# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_api_auditregistration_v1alpha1_audit_sink_list import IoK8sApiAuditregistrationV1alpha1AuditSinkList  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiAuditregistrationV1alpha1AuditSinkList(unittest.TestCase):
    """IoK8sApiAuditregistrationV1alpha1AuditSinkList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiAuditregistrationV1alpha1AuditSinkList(self):
        """Test IoK8sApiAuditregistrationV1alpha1AuditSinkList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_api_auditregistration_v1alpha1_audit_sink_list.IoK8sApiAuditregistrationV1alpha1AuditSinkList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
