# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_api_authentication_v1_token_review_status import IoK8sApiAuthenticationV1TokenReviewStatus  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiAuthenticationV1TokenReviewStatus(unittest.TestCase):
    """IoK8sApiAuthenticationV1TokenReviewStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiAuthenticationV1TokenReviewStatus(self):
        """Test IoK8sApiAuthenticationV1TokenReviewStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_api_authentication_v1_token_review_status.IoK8sApiAuthenticationV1TokenReviewStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
