# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_api_settings_v1alpha1_pod_preset_list import IoK8sApiSettingsV1alpha1PodPresetList  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiSettingsV1alpha1PodPresetList(unittest.TestCase):
    """IoK8sApiSettingsV1alpha1PodPresetList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiSettingsV1alpha1PodPresetList(self):
        """Test IoK8sApiSettingsV1alpha1PodPresetList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_api_settings_v1alpha1_pod_preset_list.IoK8sApiSettingsV1alpha1PodPresetList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
