# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_api_node_v1beta1_runtime_class_list import IoK8sApiNodeV1beta1RuntimeClassList  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiNodeV1beta1RuntimeClassList(unittest.TestCase):
    """IoK8sApiNodeV1beta1RuntimeClassList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiNodeV1beta1RuntimeClassList(self):
        """Test IoK8sApiNodeV1beta1RuntimeClassList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_api_node_v1beta1_runtime_class_list.IoK8sApiNodeV1beta1RuntimeClassList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
