# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from api.authorization_v1beta1_api import AuthorizationV1beta1Api  # noqa: E501
from argo.rest import ApiException


class TestAuthorizationV1beta1Api(unittest.TestCase):
    """AuthorizationV1beta1Api unit test stubs"""

    def setUp(self):
        self.api = api.authorization_v1beta1_api.AuthorizationV1beta1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_authorization_v1beta1_namespaced_local_subject_access_review(self):
        """Test case for create_authorization_v1beta1_namespaced_local_subject_access_review

        """
        pass

    def test_create_authorization_v1beta1_self_subject_access_review(self):
        """Test case for create_authorization_v1beta1_self_subject_access_review

        """
        pass

    def test_create_authorization_v1beta1_self_subject_rules_review(self):
        """Test case for create_authorization_v1beta1_self_subject_rules_review

        """
        pass

    def test_create_authorization_v1beta1_subject_access_review(self):
        """Test case for create_authorization_v1beta1_subject_access_review

        """
        pass

    def test_get_authorization_v1beta1_api_resources(self):
        """Test case for get_authorization_v1beta1_api_resources

        """
        pass


if __name__ == '__main__':
    unittest.main()
