# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_kube_aggregator_pkg_apis_apiregistration_v1_api_service_spec import IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceSpec  # noqa: E501
from argo.rest import ApiException


class TestIoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceSpec(unittest.TestCase):
    """IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceSpec(self):
        """Test IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_kube_aggregator_pkg_apis_apiregistration_v1_api_service_spec.IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
