# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from api.coordination_v1_api import CoordinationV1Api  # noqa: E501
from argo.rest import ApiException


class TestCoordinationV1Api(unittest.TestCase):
    """CoordinationV1Api unit test stubs"""

    def setUp(self):
        self.api = api.coordination_v1_api.CoordinationV1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_coordination_v1_namespaced_lease(self):
        """Test case for create_coordination_v1_namespaced_lease

        """
        pass

    def test_delete_coordination_v1_collection_namespaced_lease(self):
        """Test case for delete_coordination_v1_collection_namespaced_lease

        """
        pass

    def test_delete_coordination_v1_namespaced_lease(self):
        """Test case for delete_coordination_v1_namespaced_lease

        """
        pass

    def test_get_coordination_v1_api_resources(self):
        """Test case for get_coordination_v1_api_resources

        """
        pass

    def test_list_coordination_v1_lease_for_all_namespaces(self):
        """Test case for list_coordination_v1_lease_for_all_namespaces

        """
        pass

    def test_list_coordination_v1_namespaced_lease(self):
        """Test case for list_coordination_v1_namespaced_lease

        """
        pass

    def test_patch_coordination_v1_namespaced_lease(self):
        """Test case for patch_coordination_v1_namespaced_lease

        """
        pass

    def test_read_coordination_v1_namespaced_lease(self):
        """Test case for read_coordination_v1_namespaced_lease

        """
        pass

    def test_replace_coordination_v1_namespaced_lease(self):
        """Test case for replace_coordination_v1_namespaced_lease

        """
        pass

    def test_watch_coordination_v1_lease_list_for_all_namespaces(self):
        """Test case for watch_coordination_v1_lease_list_for_all_namespaces

        """
        pass

    def test_watch_coordination_v1_namespaced_lease(self):
        """Test case for watch_coordination_v1_namespaced_lease

        """
        pass

    def test_watch_coordination_v1_namespaced_lease_list(self):
        """Test case for watch_coordination_v1_namespaced_lease_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
