# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from api.apiextensions_v1beta1_api import ApiextensionsV1beta1Api  # noqa: E501
from argo.rest import ApiException


class TestApiextensionsV1beta1Api(unittest.TestCase):
    """ApiextensionsV1beta1Api unit test stubs"""

    def setUp(self):
        self.api = api.apiextensions_v1beta1_api.ApiextensionsV1beta1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_apiextensions_v1beta1_custom_resource_definition(self):
        """Test case for create_apiextensions_v1beta1_custom_resource_definition

        """
        pass

    def test_delete_apiextensions_v1beta1_collection_custom_resource_definition(self):
        """Test case for delete_apiextensions_v1beta1_collection_custom_resource_definition

        """
        pass

    def test_delete_apiextensions_v1beta1_custom_resource_definition(self):
        """Test case for delete_apiextensions_v1beta1_custom_resource_definition

        """
        pass

    def test_get_apiextensions_v1beta1_api_resources(self):
        """Test case for get_apiextensions_v1beta1_api_resources

        """
        pass

    def test_list_apiextensions_v1beta1_custom_resource_definition(self):
        """Test case for list_apiextensions_v1beta1_custom_resource_definition

        """
        pass

    def test_patch_apiextensions_v1beta1_custom_resource_definition(self):
        """Test case for patch_apiextensions_v1beta1_custom_resource_definition

        """
        pass

    def test_patch_apiextensions_v1beta1_custom_resource_definition_status(self):
        """Test case for patch_apiextensions_v1beta1_custom_resource_definition_status

        """
        pass

    def test_read_apiextensions_v1beta1_custom_resource_definition(self):
        """Test case for read_apiextensions_v1beta1_custom_resource_definition

        """
        pass

    def test_read_apiextensions_v1beta1_custom_resource_definition_status(self):
        """Test case for read_apiextensions_v1beta1_custom_resource_definition_status

        """
        pass

    def test_replace_apiextensions_v1beta1_custom_resource_definition(self):
        """Test case for replace_apiextensions_v1beta1_custom_resource_definition

        """
        pass

    def test_replace_apiextensions_v1beta1_custom_resource_definition_status(self):
        """Test case for replace_apiextensions_v1beta1_custom_resource_definition_status

        """
        pass

    def test_watch_apiextensions_v1beta1_custom_resource_definition(self):
        """Test case for watch_apiextensions_v1beta1_custom_resource_definition

        """
        pass

    def test_watch_apiextensions_v1beta1_custom_resource_definition_list(self):
        """Test case for watch_apiextensions_v1beta1_custom_resource_definition_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
