# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_api_policy_v1beta1_id_range import IoK8sApiPolicyV1beta1IDRange  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiPolicyV1beta1IDRange(unittest.TestCase):
    """IoK8sApiPolicyV1beta1IDRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiPolicyV1beta1IDRange(self):
        """Test IoK8sApiPolicyV1beta1IDRange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_api_policy_v1beta1_id_range.IoK8sApiPolicyV1beta1IDRange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
