# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_api_batch_v1beta1_job_template_spec import IoK8sApiBatchV1beta1JobTemplateSpec  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiBatchV1beta1JobTemplateSpec(unittest.TestCase):
    """IoK8sApiBatchV1beta1JobTemplateSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiBatchV1beta1JobTemplateSpec(self):
        """Test IoK8sApiBatchV1beta1JobTemplateSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_api_batch_v1beta1_job_template_spec.IoK8sApiBatchV1beta1JobTemplateSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
