# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from api.storage_v1_api import StorageV1Api  # noqa: E501
from argo.rest import ApiException


class TestStorageV1Api(unittest.TestCase):
    """StorageV1Api unit test stubs"""

    def setUp(self):
        self.api = api.storage_v1_api.StorageV1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_storage_v1_storage_class(self):
        """Test case for create_storage_v1_storage_class

        """
        pass

    def test_create_storage_v1_volume_attachment(self):
        """Test case for create_storage_v1_volume_attachment

        """
        pass

    def test_delete_storage_v1_collection_storage_class(self):
        """Test case for delete_storage_v1_collection_storage_class

        """
        pass

    def test_delete_storage_v1_collection_volume_attachment(self):
        """Test case for delete_storage_v1_collection_volume_attachment

        """
        pass

    def test_delete_storage_v1_storage_class(self):
        """Test case for delete_storage_v1_storage_class

        """
        pass

    def test_delete_storage_v1_volume_attachment(self):
        """Test case for delete_storage_v1_volume_attachment

        """
        pass

    def test_get_storage_v1_api_resources(self):
        """Test case for get_storage_v1_api_resources

        """
        pass

    def test_list_storage_v1_storage_class(self):
        """Test case for list_storage_v1_storage_class

        """
        pass

    def test_list_storage_v1_volume_attachment(self):
        """Test case for list_storage_v1_volume_attachment

        """
        pass

    def test_patch_storage_v1_storage_class(self):
        """Test case for patch_storage_v1_storage_class

        """
        pass

    def test_patch_storage_v1_volume_attachment(self):
        """Test case for patch_storage_v1_volume_attachment

        """
        pass

    def test_patch_storage_v1_volume_attachment_status(self):
        """Test case for patch_storage_v1_volume_attachment_status

        """
        pass

    def test_read_storage_v1_storage_class(self):
        """Test case for read_storage_v1_storage_class

        """
        pass

    def test_read_storage_v1_volume_attachment(self):
        """Test case for read_storage_v1_volume_attachment

        """
        pass

    def test_read_storage_v1_volume_attachment_status(self):
        """Test case for read_storage_v1_volume_attachment_status

        """
        pass

    def test_replace_storage_v1_storage_class(self):
        """Test case for replace_storage_v1_storage_class

        """
        pass

    def test_replace_storage_v1_volume_attachment(self):
        """Test case for replace_storage_v1_volume_attachment

        """
        pass

    def test_replace_storage_v1_volume_attachment_status(self):
        """Test case for replace_storage_v1_volume_attachment_status

        """
        pass

    def test_watch_storage_v1_storage_class(self):
        """Test case for watch_storage_v1_storage_class

        """
        pass

    def test_watch_storage_v1_storage_class_list(self):
        """Test case for watch_storage_v1_storage_class_list

        """
        pass

    def test_watch_storage_v1_volume_attachment(self):
        """Test case for watch_storage_v1_volume_attachment

        """
        pass

    def test_watch_storage_v1_volume_attachment_list(self):
        """Test case for watch_storage_v1_volume_attachment_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
