# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1beta1_webhook_client_config import IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1WebhookClientConfig  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1WebhookClientConfig(unittest.TestCase):
    """IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1WebhookClientConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1WebhookClientConfig(self):
        """Test IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1WebhookClientConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1beta1_webhook_client_config.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1WebhookClientConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
