# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_apimachinery_pkg_apis_meta_v1_object_meta import IoK8sApimachineryPkgApisMetaV1ObjectMeta  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApimachineryPkgApisMetaV1ObjectMeta(unittest.TestCase):
    """IoK8sApimachineryPkgApisMetaV1ObjectMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgApisMetaV1ObjectMeta(self):
        """Test IoK8sApimachineryPkgApisMetaV1ObjectMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_apimachinery_pkg_apis_meta_v1_object_meta.IoK8sApimachineryPkgApisMetaV1ObjectMeta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
