# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_kube_aggregator_pkg_apis_apiregistration_v1beta1_api_service_condition import IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceCondition  # noqa: E501
from argo.rest import ApiException


class TestIoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceCondition(unittest.TestCase):
    """IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceCondition(self):
        """Test IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceCondition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_kube_aggregator_pkg_apis_apiregistration_v1beta1_api_service_condition.IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceCondition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
