# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from api.node_v1alpha1_api import NodeV1alpha1Api  # noqa: E501
from argo.rest import ApiException


class TestNodeV1alpha1Api(unittest.TestCase):
    """NodeV1alpha1Api unit test stubs"""

    def setUp(self):
        self.api = api.node_v1alpha1_api.NodeV1alpha1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_node_v1alpha1_runtime_class(self):
        """Test case for create_node_v1alpha1_runtime_class

        """
        pass

    def test_delete_node_v1alpha1_collection_runtime_class(self):
        """Test case for delete_node_v1alpha1_collection_runtime_class

        """
        pass

    def test_delete_node_v1alpha1_runtime_class(self):
        """Test case for delete_node_v1alpha1_runtime_class

        """
        pass

    def test_get_node_v1alpha1_api_resources(self):
        """Test case for get_node_v1alpha1_api_resources

        """
        pass

    def test_list_node_v1alpha1_runtime_class(self):
        """Test case for list_node_v1alpha1_runtime_class

        """
        pass

    def test_patch_node_v1alpha1_runtime_class(self):
        """Test case for patch_node_v1alpha1_runtime_class

        """
        pass

    def test_read_node_v1alpha1_runtime_class(self):
        """Test case for read_node_v1alpha1_runtime_class

        """
        pass

    def test_replace_node_v1alpha1_runtime_class(self):
        """Test case for replace_node_v1alpha1_runtime_class

        """
        pass

    def test_watch_node_v1alpha1_runtime_class(self):
        """Test case for watch_node_v1alpha1_runtime_class

        """
        pass

    def test_watch_node_v1alpha1_runtime_class_list(self):
        """Test case for watch_node_v1alpha1_runtime_class_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
