# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_api_autoscaling_v1_horizontal_pod_autoscaler_spec import IoK8sApiAutoscalingV1HorizontalPodAutoscalerSpec  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiAutoscalingV1HorizontalPodAutoscalerSpec(unittest.TestCase):
    """IoK8sApiAutoscalingV1HorizontalPodAutoscalerSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiAutoscalingV1HorizontalPodAutoscalerSpec(self):
        """Test IoK8sApiAutoscalingV1HorizontalPodAutoscalerSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_api_autoscaling_v1_horizontal_pod_autoscaler_spec.IoK8sApiAutoscalingV1HorizontalPodAutoscalerSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
