# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from api.authorization_api import AuthorizationApi  # noqa: E501
from argo.rest import ApiException


class TestAuthorizationApi(unittest.TestCase):
    """AuthorizationApi unit test stubs"""

    def setUp(self):
        self.api = api.authorization_api.AuthorizationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_authorization_api_group(self):
        """Test case for get_authorization_api_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
