# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_api_autoscaling_v2beta2_cross_version_object_reference import IoK8sApiAutoscalingV2beta2CrossVersionObjectReference  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiAutoscalingV2beta2CrossVersionObjectReference(unittest.TestCase):
    """IoK8sApiAutoscalingV2beta2CrossVersionObjectReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiAutoscalingV2beta2CrossVersionObjectReference(self):
        """Test IoK8sApiAutoscalingV2beta2CrossVersionObjectReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_api_autoscaling_v2beta2_cross_version_object_reference.IoK8sApiAutoscalingV2beta2CrossVersionObjectReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
