# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from api.apiregistration_v1beta1_api import ApiregistrationV1beta1Api  # noqa: E501
from argo.rest import ApiException


class TestApiregistrationV1beta1Api(unittest.TestCase):
    """ApiregistrationV1beta1Api unit test stubs"""

    def setUp(self):
        self.api = api.apiregistration_v1beta1_api.ApiregistrationV1beta1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_apiregistration_v1beta1_api_service(self):
        """Test case for create_apiregistration_v1beta1_api_service

        """
        pass

    def test_delete_apiregistration_v1beta1_api_service(self):
        """Test case for delete_apiregistration_v1beta1_api_service

        """
        pass

    def test_delete_apiregistration_v1beta1_collection_api_service(self):
        """Test case for delete_apiregistration_v1beta1_collection_api_service

        """
        pass

    def test_get_apiregistration_v1beta1_api_resources(self):
        """Test case for get_apiregistration_v1beta1_api_resources

        """
        pass

    def test_list_apiregistration_v1beta1_api_service(self):
        """Test case for list_apiregistration_v1beta1_api_service

        """
        pass

    def test_patch_apiregistration_v1beta1_api_service(self):
        """Test case for patch_apiregistration_v1beta1_api_service

        """
        pass

    def test_patch_apiregistration_v1beta1_api_service_status(self):
        """Test case for patch_apiregistration_v1beta1_api_service_status

        """
        pass

    def test_read_apiregistration_v1beta1_api_service(self):
        """Test case for read_apiregistration_v1beta1_api_service

        """
        pass

    def test_read_apiregistration_v1beta1_api_service_status(self):
        """Test case for read_apiregistration_v1beta1_api_service_status

        """
        pass

    def test_replace_apiregistration_v1beta1_api_service(self):
        """Test case for replace_apiregistration_v1beta1_api_service

        """
        pass

    def test_replace_apiregistration_v1beta1_api_service_status(self):
        """Test case for replace_apiregistration_v1beta1_api_service_status

        """
        pass

    def test_watch_apiregistration_v1beta1_api_service(self):
        """Test case for watch_apiregistration_v1beta1_api_service

        """
        pass

    def test_watch_apiregistration_v1beta1_api_service_list(self):
        """Test case for watch_apiregistration_v1beta1_api_service_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
