# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from api.admissionregistration_v1beta1_api import AdmissionregistrationV1beta1Api  # noqa: E501
from argo.rest import ApiException


class TestAdmissionregistrationV1beta1Api(unittest.TestCase):
    """AdmissionregistrationV1beta1Api unit test stubs"""

    def setUp(self):
        self.api = api.admissionregistration_v1beta1_api.AdmissionregistrationV1beta1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_admissionregistration_v1beta1_mutating_webhook_configuration(self):
        """Test case for create_admissionregistration_v1beta1_mutating_webhook_configuration

        """
        pass

    def test_create_admissionregistration_v1beta1_validating_webhook_configuration(self):
        """Test case for create_admissionregistration_v1beta1_validating_webhook_configuration

        """
        pass

    def test_delete_admissionregistration_v1beta1_collection_mutating_webhook_configuration(self):
        """Test case for delete_admissionregistration_v1beta1_collection_mutating_webhook_configuration

        """
        pass

    def test_delete_admissionregistration_v1beta1_collection_validating_webhook_configuration(self):
        """Test case for delete_admissionregistration_v1beta1_collection_validating_webhook_configuration

        """
        pass

    def test_delete_admissionregistration_v1beta1_mutating_webhook_configuration(self):
        """Test case for delete_admissionregistration_v1beta1_mutating_webhook_configuration

        """
        pass

    def test_delete_admissionregistration_v1beta1_validating_webhook_configuration(self):
        """Test case for delete_admissionregistration_v1beta1_validating_webhook_configuration

        """
        pass

    def test_get_admissionregistration_v1beta1_api_resources(self):
        """Test case for get_admissionregistration_v1beta1_api_resources

        """
        pass

    def test_list_admissionregistration_v1beta1_mutating_webhook_configuration(self):
        """Test case for list_admissionregistration_v1beta1_mutating_webhook_configuration

        """
        pass

    def test_list_admissionregistration_v1beta1_validating_webhook_configuration(self):
        """Test case for list_admissionregistration_v1beta1_validating_webhook_configuration

        """
        pass

    def test_patch_admissionregistration_v1beta1_mutating_webhook_configuration(self):
        """Test case for patch_admissionregistration_v1beta1_mutating_webhook_configuration

        """
        pass

    def test_patch_admissionregistration_v1beta1_validating_webhook_configuration(self):
        """Test case for patch_admissionregistration_v1beta1_validating_webhook_configuration

        """
        pass

    def test_read_admissionregistration_v1beta1_mutating_webhook_configuration(self):
        """Test case for read_admissionregistration_v1beta1_mutating_webhook_configuration

        """
        pass

    def test_read_admissionregistration_v1beta1_validating_webhook_configuration(self):
        """Test case for read_admissionregistration_v1beta1_validating_webhook_configuration

        """
        pass

    def test_replace_admissionregistration_v1beta1_mutating_webhook_configuration(self):
        """Test case for replace_admissionregistration_v1beta1_mutating_webhook_configuration

        """
        pass

    def test_replace_admissionregistration_v1beta1_validating_webhook_configuration(self):
        """Test case for replace_admissionregistration_v1beta1_validating_webhook_configuration

        """
        pass

    def test_watch_admissionregistration_v1beta1_mutating_webhook_configuration(self):
        """Test case for watch_admissionregistration_v1beta1_mutating_webhook_configuration

        """
        pass

    def test_watch_admissionregistration_v1beta1_mutating_webhook_configuration_list(self):
        """Test case for watch_admissionregistration_v1beta1_mutating_webhook_configuration_list

        """
        pass

    def test_watch_admissionregistration_v1beta1_validating_webhook_configuration(self):
        """Test case for watch_admissionregistration_v1beta1_validating_webhook_configuration

        """
        pass

    def test_watch_admissionregistration_v1beta1_validating_webhook_configuration_list(self):
        """Test case for watch_admissionregistration_v1beta1_validating_webhook_configuration_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
