# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_apimachinery_pkg_version_info import IoK8sApimachineryPkgVersionInfo  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApimachineryPkgVersionInfo(unittest.TestCase):
    """IoK8sApimachineryPkgVersionInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgVersionInfo(self):
        """Test IoK8sApimachineryPkgVersionInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_apimachinery_pkg_version_info.IoK8sApimachineryPkgVersionInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
