# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_api_apps_v1_rolling_update_stateful_set_strategy import IoK8sApiAppsV1RollingUpdateStatefulSetStrategy  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiAppsV1RollingUpdateStatefulSetStrategy(unittest.TestCase):
    """IoK8sApiAppsV1RollingUpdateStatefulSetStrategy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiAppsV1RollingUpdateStatefulSetStrategy(self):
        """Test IoK8sApiAppsV1RollingUpdateStatefulSetStrategy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_api_apps_v1_rolling_update_stateful_set_strategy.IoK8sApiAppsV1RollingUpdateStatefulSetStrategy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
