# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from api.policy_v1beta1_api import PolicyV1beta1Api  # noqa: E501
from argo.rest import ApiException


class TestPolicyV1beta1Api(unittest.TestCase):
    """PolicyV1beta1Api unit test stubs"""

    def setUp(self):
        self.api = api.policy_v1beta1_api.PolicyV1beta1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_policy_v1beta1_namespaced_pod_disruption_budget(self):
        """Test case for create_policy_v1beta1_namespaced_pod_disruption_budget

        """
        pass

    def test_create_policy_v1beta1_pod_security_policy(self):
        """Test case for create_policy_v1beta1_pod_security_policy

        """
        pass

    def test_delete_policy_v1beta1_collection_namespaced_pod_disruption_budget(self):
        """Test case for delete_policy_v1beta1_collection_namespaced_pod_disruption_budget

        """
        pass

    def test_delete_policy_v1beta1_collection_pod_security_policy(self):
        """Test case for delete_policy_v1beta1_collection_pod_security_policy

        """
        pass

    def test_delete_policy_v1beta1_namespaced_pod_disruption_budget(self):
        """Test case for delete_policy_v1beta1_namespaced_pod_disruption_budget

        """
        pass

    def test_delete_policy_v1beta1_pod_security_policy(self):
        """Test case for delete_policy_v1beta1_pod_security_policy

        """
        pass

    def test_get_policy_v1beta1_api_resources(self):
        """Test case for get_policy_v1beta1_api_resources

        """
        pass

    def test_list_policy_v1beta1_namespaced_pod_disruption_budget(self):
        """Test case for list_policy_v1beta1_namespaced_pod_disruption_budget

        """
        pass

    def test_list_policy_v1beta1_pod_disruption_budget_for_all_namespaces(self):
        """Test case for list_policy_v1beta1_pod_disruption_budget_for_all_namespaces

        """
        pass

    def test_list_policy_v1beta1_pod_security_policy(self):
        """Test case for list_policy_v1beta1_pod_security_policy

        """
        pass

    def test_patch_policy_v1beta1_namespaced_pod_disruption_budget(self):
        """Test case for patch_policy_v1beta1_namespaced_pod_disruption_budget

        """
        pass

    def test_patch_policy_v1beta1_namespaced_pod_disruption_budget_status(self):
        """Test case for patch_policy_v1beta1_namespaced_pod_disruption_budget_status

        """
        pass

    def test_patch_policy_v1beta1_pod_security_policy(self):
        """Test case for patch_policy_v1beta1_pod_security_policy

        """
        pass

    def test_read_policy_v1beta1_namespaced_pod_disruption_budget(self):
        """Test case for read_policy_v1beta1_namespaced_pod_disruption_budget

        """
        pass

    def test_read_policy_v1beta1_namespaced_pod_disruption_budget_status(self):
        """Test case for read_policy_v1beta1_namespaced_pod_disruption_budget_status

        """
        pass

    def test_read_policy_v1beta1_pod_security_policy(self):
        """Test case for read_policy_v1beta1_pod_security_policy

        """
        pass

    def test_replace_policy_v1beta1_namespaced_pod_disruption_budget(self):
        """Test case for replace_policy_v1beta1_namespaced_pod_disruption_budget

        """
        pass

    def test_replace_policy_v1beta1_namespaced_pod_disruption_budget_status(self):
        """Test case for replace_policy_v1beta1_namespaced_pod_disruption_budget_status

        """
        pass

    def test_replace_policy_v1beta1_pod_security_policy(self):
        """Test case for replace_policy_v1beta1_pod_security_policy

        """
        pass

    def test_watch_policy_v1beta1_namespaced_pod_disruption_budget(self):
        """Test case for watch_policy_v1beta1_namespaced_pod_disruption_budget

        """
        pass

    def test_watch_policy_v1beta1_namespaced_pod_disruption_budget_list(self):
        """Test case for watch_policy_v1beta1_namespaced_pod_disruption_budget_list

        """
        pass

    def test_watch_policy_v1beta1_pod_disruption_budget_list_for_all_namespaces(self):
        """Test case for watch_policy_v1beta1_pod_disruption_budget_list_for_all_namespaces

        """
        pass

    def test_watch_policy_v1beta1_pod_security_policy(self):
        """Test case for watch_policy_v1beta1_pod_security_policy

        """
        pass

    def test_watch_policy_v1beta1_pod_security_policy_list(self):
        """Test case for watch_policy_v1beta1_pod_security_policy_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
