# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from api.scheduling_v1_api import SchedulingV1Api  # noqa: E501
from argo.rest import ApiException


class TestSchedulingV1Api(unittest.TestCase):
    """SchedulingV1Api unit test stubs"""

    def setUp(self):
        self.api = api.scheduling_v1_api.SchedulingV1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_scheduling_v1_priority_class(self):
        """Test case for create_scheduling_v1_priority_class

        """
        pass

    def test_delete_scheduling_v1_collection_priority_class(self):
        """Test case for delete_scheduling_v1_collection_priority_class

        """
        pass

    def test_delete_scheduling_v1_priority_class(self):
        """Test case for delete_scheduling_v1_priority_class

        """
        pass

    def test_get_scheduling_v1_api_resources(self):
        """Test case for get_scheduling_v1_api_resources

        """
        pass

    def test_list_scheduling_v1_priority_class(self):
        """Test case for list_scheduling_v1_priority_class

        """
        pass

    def test_patch_scheduling_v1_priority_class(self):
        """Test case for patch_scheduling_v1_priority_class

        """
        pass

    def test_read_scheduling_v1_priority_class(self):
        """Test case for read_scheduling_v1_priority_class

        """
        pass

    def test_replace_scheduling_v1_priority_class(self):
        """Test case for replace_scheduling_v1_priority_class

        """
        pass

    def test_watch_scheduling_v1_priority_class(self):
        """Test case for watch_scheduling_v1_priority_class

        """
        pass

    def test_watch_scheduling_v1_priority_class_list(self):
        """Test case for watch_scheduling_v1_priority_class_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
