# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_api_authorization_v1_subject_access_review_spec import IoK8sApiAuthorizationV1SubjectAccessReviewSpec  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiAuthorizationV1SubjectAccessReviewSpec(unittest.TestCase):
    """IoK8sApiAuthorizationV1SubjectAccessReviewSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiAuthorizationV1SubjectAccessReviewSpec(self):
        """Test IoK8sApiAuthorizationV1SubjectAccessReviewSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_api_authorization_v1_subject_access_review_spec.IoK8sApiAuthorizationV1SubjectAccessReviewSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
