# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from api.events_v1beta1_api import EventsV1beta1Api  # noqa: E501
from argo.rest import ApiException


class TestEventsV1beta1Api(unittest.TestCase):
    """EventsV1beta1Api unit test stubs"""

    def setUp(self):
        self.api = api.events_v1beta1_api.EventsV1beta1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_events_v1beta1_namespaced_event(self):
        """Test case for create_events_v1beta1_namespaced_event

        """
        pass

    def test_delete_events_v1beta1_collection_namespaced_event(self):
        """Test case for delete_events_v1beta1_collection_namespaced_event

        """
        pass

    def test_delete_events_v1beta1_namespaced_event(self):
        """Test case for delete_events_v1beta1_namespaced_event

        """
        pass

    def test_get_events_v1beta1_api_resources(self):
        """Test case for get_events_v1beta1_api_resources

        """
        pass

    def test_list_events_v1beta1_event_for_all_namespaces(self):
        """Test case for list_events_v1beta1_event_for_all_namespaces

        """
        pass

    def test_list_events_v1beta1_namespaced_event(self):
        """Test case for list_events_v1beta1_namespaced_event

        """
        pass

    def test_patch_events_v1beta1_namespaced_event(self):
        """Test case for patch_events_v1beta1_namespaced_event

        """
        pass

    def test_read_events_v1beta1_namespaced_event(self):
        """Test case for read_events_v1beta1_namespaced_event

        """
        pass

    def test_replace_events_v1beta1_namespaced_event(self):
        """Test case for replace_events_v1beta1_namespaced_event

        """
        pass

    def test_watch_events_v1beta1_event_list_for_all_namespaces(self):
        """Test case for watch_events_v1beta1_event_list_for_all_namespaces

        """
        pass

    def test_watch_events_v1beta1_namespaced_event(self):
        """Test case for watch_events_v1beta1_namespaced_event

        """
        pass

    def test_watch_events_v1beta1_namespaced_event_list(self):
        """Test case for watch_events_v1beta1_namespaced_event_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
