# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from api.apps_v1beta2_api import AppsV1beta2Api  # noqa: E501
from argo.rest import ApiException


class TestAppsV1beta2Api(unittest.TestCase):
    """AppsV1beta2Api unit test stubs"""

    def setUp(self):
        self.api = api.apps_v1beta2_api.AppsV1beta2Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_apps_v1beta2_namespaced_controller_revision(self):
        """Test case for create_apps_v1beta2_namespaced_controller_revision

        """
        pass

    def test_create_apps_v1beta2_namespaced_daemon_set(self):
        """Test case for create_apps_v1beta2_namespaced_daemon_set

        """
        pass

    def test_create_apps_v1beta2_namespaced_deployment(self):
        """Test case for create_apps_v1beta2_namespaced_deployment

        """
        pass

    def test_create_apps_v1beta2_namespaced_replica_set(self):
        """Test case for create_apps_v1beta2_namespaced_replica_set

        """
        pass

    def test_create_apps_v1beta2_namespaced_stateful_set(self):
        """Test case for create_apps_v1beta2_namespaced_stateful_set

        """
        pass

    def test_delete_apps_v1beta2_collection_namespaced_controller_revision(self):
        """Test case for delete_apps_v1beta2_collection_namespaced_controller_revision

        """
        pass

    def test_delete_apps_v1beta2_collection_namespaced_daemon_set(self):
        """Test case for delete_apps_v1beta2_collection_namespaced_daemon_set

        """
        pass

    def test_delete_apps_v1beta2_collection_namespaced_deployment(self):
        """Test case for delete_apps_v1beta2_collection_namespaced_deployment

        """
        pass

    def test_delete_apps_v1beta2_collection_namespaced_replica_set(self):
        """Test case for delete_apps_v1beta2_collection_namespaced_replica_set

        """
        pass

    def test_delete_apps_v1beta2_collection_namespaced_stateful_set(self):
        """Test case for delete_apps_v1beta2_collection_namespaced_stateful_set

        """
        pass

    def test_delete_apps_v1beta2_namespaced_controller_revision(self):
        """Test case for delete_apps_v1beta2_namespaced_controller_revision

        """
        pass

    def test_delete_apps_v1beta2_namespaced_daemon_set(self):
        """Test case for delete_apps_v1beta2_namespaced_daemon_set

        """
        pass

    def test_delete_apps_v1beta2_namespaced_deployment(self):
        """Test case for delete_apps_v1beta2_namespaced_deployment

        """
        pass

    def test_delete_apps_v1beta2_namespaced_replica_set(self):
        """Test case for delete_apps_v1beta2_namespaced_replica_set

        """
        pass

    def test_delete_apps_v1beta2_namespaced_stateful_set(self):
        """Test case for delete_apps_v1beta2_namespaced_stateful_set

        """
        pass

    def test_get_apps_v1beta2_api_resources(self):
        """Test case for get_apps_v1beta2_api_resources

        """
        pass

    def test_list_apps_v1beta2_controller_revision_for_all_namespaces(self):
        """Test case for list_apps_v1beta2_controller_revision_for_all_namespaces

        """
        pass

    def test_list_apps_v1beta2_daemon_set_for_all_namespaces(self):
        """Test case for list_apps_v1beta2_daemon_set_for_all_namespaces

        """
        pass

    def test_list_apps_v1beta2_deployment_for_all_namespaces(self):
        """Test case for list_apps_v1beta2_deployment_for_all_namespaces

        """
        pass

    def test_list_apps_v1beta2_namespaced_controller_revision(self):
        """Test case for list_apps_v1beta2_namespaced_controller_revision

        """
        pass

    def test_list_apps_v1beta2_namespaced_daemon_set(self):
        """Test case for list_apps_v1beta2_namespaced_daemon_set

        """
        pass

    def test_list_apps_v1beta2_namespaced_deployment(self):
        """Test case for list_apps_v1beta2_namespaced_deployment

        """
        pass

    def test_list_apps_v1beta2_namespaced_replica_set(self):
        """Test case for list_apps_v1beta2_namespaced_replica_set

        """
        pass

    def test_list_apps_v1beta2_namespaced_stateful_set(self):
        """Test case for list_apps_v1beta2_namespaced_stateful_set

        """
        pass

    def test_list_apps_v1beta2_replica_set_for_all_namespaces(self):
        """Test case for list_apps_v1beta2_replica_set_for_all_namespaces

        """
        pass

    def test_list_apps_v1beta2_stateful_set_for_all_namespaces(self):
        """Test case for list_apps_v1beta2_stateful_set_for_all_namespaces

        """
        pass

    def test_patch_apps_v1beta2_namespaced_controller_revision(self):
        """Test case for patch_apps_v1beta2_namespaced_controller_revision

        """
        pass

    def test_patch_apps_v1beta2_namespaced_daemon_set(self):
        """Test case for patch_apps_v1beta2_namespaced_daemon_set

        """
        pass

    def test_patch_apps_v1beta2_namespaced_daemon_set_status(self):
        """Test case for patch_apps_v1beta2_namespaced_daemon_set_status

        """
        pass

    def test_patch_apps_v1beta2_namespaced_deployment(self):
        """Test case for patch_apps_v1beta2_namespaced_deployment

        """
        pass

    def test_patch_apps_v1beta2_namespaced_deployment_scale(self):
        """Test case for patch_apps_v1beta2_namespaced_deployment_scale

        """
        pass

    def test_patch_apps_v1beta2_namespaced_deployment_status(self):
        """Test case for patch_apps_v1beta2_namespaced_deployment_status

        """
        pass

    def test_patch_apps_v1beta2_namespaced_replica_set(self):
        """Test case for patch_apps_v1beta2_namespaced_replica_set

        """
        pass

    def test_patch_apps_v1beta2_namespaced_replica_set_scale(self):
        """Test case for patch_apps_v1beta2_namespaced_replica_set_scale

        """
        pass

    def test_patch_apps_v1beta2_namespaced_replica_set_status(self):
        """Test case for patch_apps_v1beta2_namespaced_replica_set_status

        """
        pass

    def test_patch_apps_v1beta2_namespaced_stateful_set(self):
        """Test case for patch_apps_v1beta2_namespaced_stateful_set

        """
        pass

    def test_patch_apps_v1beta2_namespaced_stateful_set_scale(self):
        """Test case for patch_apps_v1beta2_namespaced_stateful_set_scale

        """
        pass

    def test_patch_apps_v1beta2_namespaced_stateful_set_status(self):
        """Test case for patch_apps_v1beta2_namespaced_stateful_set_status

        """
        pass

    def test_read_apps_v1beta2_namespaced_controller_revision(self):
        """Test case for read_apps_v1beta2_namespaced_controller_revision

        """
        pass

    def test_read_apps_v1beta2_namespaced_daemon_set(self):
        """Test case for read_apps_v1beta2_namespaced_daemon_set

        """
        pass

    def test_read_apps_v1beta2_namespaced_daemon_set_status(self):
        """Test case for read_apps_v1beta2_namespaced_daemon_set_status

        """
        pass

    def test_read_apps_v1beta2_namespaced_deployment(self):
        """Test case for read_apps_v1beta2_namespaced_deployment

        """
        pass

    def test_read_apps_v1beta2_namespaced_deployment_scale(self):
        """Test case for read_apps_v1beta2_namespaced_deployment_scale

        """
        pass

    def test_read_apps_v1beta2_namespaced_deployment_status(self):
        """Test case for read_apps_v1beta2_namespaced_deployment_status

        """
        pass

    def test_read_apps_v1beta2_namespaced_replica_set(self):
        """Test case for read_apps_v1beta2_namespaced_replica_set

        """
        pass

    def test_read_apps_v1beta2_namespaced_replica_set_scale(self):
        """Test case for read_apps_v1beta2_namespaced_replica_set_scale

        """
        pass

    def test_read_apps_v1beta2_namespaced_replica_set_status(self):
        """Test case for read_apps_v1beta2_namespaced_replica_set_status

        """
        pass

    def test_read_apps_v1beta2_namespaced_stateful_set(self):
        """Test case for read_apps_v1beta2_namespaced_stateful_set

        """
        pass

    def test_read_apps_v1beta2_namespaced_stateful_set_scale(self):
        """Test case for read_apps_v1beta2_namespaced_stateful_set_scale

        """
        pass

    def test_read_apps_v1beta2_namespaced_stateful_set_status(self):
        """Test case for read_apps_v1beta2_namespaced_stateful_set_status

        """
        pass

    def test_replace_apps_v1beta2_namespaced_controller_revision(self):
        """Test case for replace_apps_v1beta2_namespaced_controller_revision

        """
        pass

    def test_replace_apps_v1beta2_namespaced_daemon_set(self):
        """Test case for replace_apps_v1beta2_namespaced_daemon_set

        """
        pass

    def test_replace_apps_v1beta2_namespaced_daemon_set_status(self):
        """Test case for replace_apps_v1beta2_namespaced_daemon_set_status

        """
        pass

    def test_replace_apps_v1beta2_namespaced_deployment(self):
        """Test case for replace_apps_v1beta2_namespaced_deployment

        """
        pass

    def test_replace_apps_v1beta2_namespaced_deployment_scale(self):
        """Test case for replace_apps_v1beta2_namespaced_deployment_scale

        """
        pass

    def test_replace_apps_v1beta2_namespaced_deployment_status(self):
        """Test case for replace_apps_v1beta2_namespaced_deployment_status

        """
        pass

    def test_replace_apps_v1beta2_namespaced_replica_set(self):
        """Test case for replace_apps_v1beta2_namespaced_replica_set

        """
        pass

    def test_replace_apps_v1beta2_namespaced_replica_set_scale(self):
        """Test case for replace_apps_v1beta2_namespaced_replica_set_scale

        """
        pass

    def test_replace_apps_v1beta2_namespaced_replica_set_status(self):
        """Test case for replace_apps_v1beta2_namespaced_replica_set_status

        """
        pass

    def test_replace_apps_v1beta2_namespaced_stateful_set(self):
        """Test case for replace_apps_v1beta2_namespaced_stateful_set

        """
        pass

    def test_replace_apps_v1beta2_namespaced_stateful_set_scale(self):
        """Test case for replace_apps_v1beta2_namespaced_stateful_set_scale

        """
        pass

    def test_replace_apps_v1beta2_namespaced_stateful_set_status(self):
        """Test case for replace_apps_v1beta2_namespaced_stateful_set_status

        """
        pass

    def test_watch_apps_v1beta2_controller_revision_list_for_all_namespaces(self):
        """Test case for watch_apps_v1beta2_controller_revision_list_for_all_namespaces

        """
        pass

    def test_watch_apps_v1beta2_daemon_set_list_for_all_namespaces(self):
        """Test case for watch_apps_v1beta2_daemon_set_list_for_all_namespaces

        """
        pass

    def test_watch_apps_v1beta2_deployment_list_for_all_namespaces(self):
        """Test case for watch_apps_v1beta2_deployment_list_for_all_namespaces

        """
        pass

    def test_watch_apps_v1beta2_namespaced_controller_revision(self):
        """Test case for watch_apps_v1beta2_namespaced_controller_revision

        """
        pass

    def test_watch_apps_v1beta2_namespaced_controller_revision_list(self):
        """Test case for watch_apps_v1beta2_namespaced_controller_revision_list

        """
        pass

    def test_watch_apps_v1beta2_namespaced_daemon_set(self):
        """Test case for watch_apps_v1beta2_namespaced_daemon_set

        """
        pass

    def test_watch_apps_v1beta2_namespaced_daemon_set_list(self):
        """Test case for watch_apps_v1beta2_namespaced_daemon_set_list

        """
        pass

    def test_watch_apps_v1beta2_namespaced_deployment(self):
        """Test case for watch_apps_v1beta2_namespaced_deployment

        """
        pass

    def test_watch_apps_v1beta2_namespaced_deployment_list(self):
        """Test case for watch_apps_v1beta2_namespaced_deployment_list

        """
        pass

    def test_watch_apps_v1beta2_namespaced_replica_set(self):
        """Test case for watch_apps_v1beta2_namespaced_replica_set

        """
        pass

    def test_watch_apps_v1beta2_namespaced_replica_set_list(self):
        """Test case for watch_apps_v1beta2_namespaced_replica_set_list

        """
        pass

    def test_watch_apps_v1beta2_namespaced_stateful_set(self):
        """Test case for watch_apps_v1beta2_namespaced_stateful_set

        """
        pass

    def test_watch_apps_v1beta2_namespaced_stateful_set_list(self):
        """Test case for watch_apps_v1beta2_namespaced_stateful_set_list

        """
        pass

    def test_watch_apps_v1beta2_replica_set_list_for_all_namespaces(self):
        """Test case for watch_apps_v1beta2_replica_set_list_for_all_namespaces

        """
        pass

    def test_watch_apps_v1beta2_stateful_set_list_for_all_namespaces(self):
        """Test case for watch_apps_v1beta2_stateful_set_list_for_all_namespaces

        """
        pass


if __name__ == '__main__':
    unittest.main()
