# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_api_events_v1beta1_event import IoK8sApiEventsV1beta1Event  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiEventsV1beta1Event(unittest.TestCase):
    """IoK8sApiEventsV1beta1Event unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiEventsV1beta1Event(self):
        """Test IoK8sApiEventsV1beta1Event"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_api_events_v1beta1_event.IoK8sApiEventsV1beta1Event()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
