# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_api_rbac_v1_cluster_role_binding import IoK8sApiRbacV1ClusterRoleBinding  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiRbacV1ClusterRoleBinding(unittest.TestCase):
    """IoK8sApiRbacV1ClusterRoleBinding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiRbacV1ClusterRoleBinding(self):
        """Test IoK8sApiRbacV1ClusterRoleBinding"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_api_rbac_v1_cluster_role_binding.IoK8sApiRbacV1ClusterRoleBinding()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
