# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_api_certificates_v1beta1_certificate_signing_request import IoK8sApiCertificatesV1beta1CertificateSigningRequest  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiCertificatesV1beta1CertificateSigningRequest(unittest.TestCase):
    """IoK8sApiCertificatesV1beta1CertificateSigningRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCertificatesV1beta1CertificateSigningRequest(self):
        """Test IoK8sApiCertificatesV1beta1CertificateSigningRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_api_certificates_v1beta1_certificate_signing_request.IoK8sApiCertificatesV1beta1CertificateSigningRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
