# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_api_storage_v1_storage_class import IoK8sApiStorageV1StorageClass  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiStorageV1StorageClass(unittest.TestCase):
    """IoK8sApiStorageV1StorageClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiStorageV1StorageClass(self):
        """Test IoK8sApiStorageV1StorageClass"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_api_storage_v1_storage_class.IoK8sApiStorageV1StorageClass()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
