# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_k8s_api_batch_v2alpha1_cron_job import IoK8sApiBatchV2alpha1CronJob  # noqa: E501
from argo.rest import ApiException


class TestIoK8sApiBatchV2alpha1CronJob(unittest.TestCase):
    """IoK8sApiBatchV2alpha1CronJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiBatchV2alpha1CronJob(self):
        """Test IoK8sApiBatchV2alpha1CronJob"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_k8s_api_batch_v2alpha1_cron_job.IoK8sApiBatchV2alpha1CronJob()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
