# coding: utf-8

"""
    Argo

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo
from models.io_argoproj_workflow_v1alpha1_inputs import IoArgoprojWorkflowV1alpha1Inputs  # noqa: E501
from argo.rest import ApiException


class TestIoArgoprojWorkflowV1alpha1Inputs(unittest.TestCase):
    """IoArgoprojWorkflowV1alpha1Inputs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoArgoprojWorkflowV1alpha1Inputs(self):
        """Test IoArgoprojWorkflowV1alpha1Inputs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.models.io_argoproj_workflow_v1alpha1_inputs.IoArgoprojWorkflowV1alpha1Inputs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
