# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from argo.models.io_k8s_apimachinery_pkg_util_intstr_int_or_string import IoK8sApimachineryPkgUtilIntstrIntOrString  # noqa: F401,E501


class IoK8sApiAppsV1RollingUpdateDaemonSet(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'max_unavailable': 'IoK8sApimachineryPkgUtilIntstrIntOrString'
    }

    attribute_map = {
        'max_unavailable': 'maxUnavailable'
    }

    def __init__(self, max_unavailable=None):  # noqa: E501
        """IoK8sApiAppsV1RollingUpdateDaemonSet - a model defined in Swagger"""  # noqa: E501
        self._max_unavailable = None
        self.discriminator = None
        if max_unavailable is not None:
            self.max_unavailable = max_unavailable

    @property
    def max_unavailable(self):
        """Gets the max_unavailable of this IoK8sApiAppsV1RollingUpdateDaemonSet.  # noqa: E501


        :return: The max_unavailable of this IoK8sApiAppsV1RollingUpdateDaemonSet.  # noqa: E501
        :rtype: IoK8sApimachineryPkgUtilIntstrIntOrString
        """
        return self._max_unavailable

    @max_unavailable.setter
    def max_unavailable(self, max_unavailable):
        """Sets the max_unavailable of this IoK8sApiAppsV1RollingUpdateDaemonSet.


        :param max_unavailable: The max_unavailable of this IoK8sApiAppsV1RollingUpdateDaemonSet.  # noqa: E501
        :type: IoK8sApimachineryPkgUtilIntstrIntOrString
        """

        self._max_unavailable = max_unavailable

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoK8sApiAppsV1RollingUpdateDaemonSet, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoK8sApiAppsV1RollingUpdateDaemonSet):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
