# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from argo.models.io_k8s_apimachinery_pkg_util_intstr_int_or_string import IoK8sApimachineryPkgUtilIntstrIntOrString  # noqa: F401,E501


class IoK8sApiNetworkingV1NetworkPolicyPort(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'port': 'IoK8sApimachineryPkgUtilIntstrIntOrString',
        'protocol': 'str'
    }

    attribute_map = {
        'port': 'port',
        'protocol': 'protocol'
    }

    def __init__(self, port=None, protocol=None):  # noqa: E501
        """IoK8sApiNetworkingV1NetworkPolicyPort - a model defined in Swagger"""  # noqa: E501
        self._port = None
        self._protocol = None
        self.discriminator = None
        if port is not None:
            self.port = port
        if protocol is not None:
            self.protocol = protocol

    @property
    def port(self):
        """Gets the port of this IoK8sApiNetworkingV1NetworkPolicyPort.  # noqa: E501


        :return: The port of this IoK8sApiNetworkingV1NetworkPolicyPort.  # noqa: E501
        :rtype: IoK8sApimachineryPkgUtilIntstrIntOrString
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this IoK8sApiNetworkingV1NetworkPolicyPort.


        :param port: The port of this IoK8sApiNetworkingV1NetworkPolicyPort.  # noqa: E501
        :type: IoK8sApimachineryPkgUtilIntstrIntOrString
        """

        self._port = port

    @property
    def protocol(self):
        """Gets the protocol of this IoK8sApiNetworkingV1NetworkPolicyPort.  # noqa: E501

        The protocol (TCP, UDP, or SCTP) which traffic must match. If not specified, this field defaults to TCP.  # noqa: E501

        :return: The protocol of this IoK8sApiNetworkingV1NetworkPolicyPort.  # noqa: E501
        :rtype: str
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol):
        """Sets the protocol of this IoK8sApiNetworkingV1NetworkPolicyPort.

        The protocol (TCP, UDP, or SCTP) which traffic must match. If not specified, this field defaults to TCP.  # noqa: E501

        :param protocol: The protocol of this IoK8sApiNetworkingV1NetworkPolicyPort.  # noqa: E501
        :type: str
        """

        self._protocol = protocol

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoK8sApiNetworkingV1NetworkPolicyPort, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoK8sApiNetworkingV1NetworkPolicyPort):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
