# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from argo.models.io_k8s_kube_aggregator_pkg_apis_apiregistration_v1_api_service_condition import IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceCondition  # noqa: F401,E501


class IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'conditions': 'list[IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceCondition]'
    }

    attribute_map = {
        'conditions': 'conditions'
    }

    def __init__(self, conditions=None):  # noqa: E501
        """IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus - a model defined in Swagger"""  # noqa: E501
        self._conditions = None
        self.discriminator = None
        if conditions is not None:
            self.conditions = conditions

    @property
    def conditions(self):
        """Gets the conditions of this IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus.  # noqa: E501

        Current service state of apiService.  # noqa: E501

        :return: The conditions of this IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus.  # noqa: E501
        :rtype: list[IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceCondition]
        """
        return self._conditions

    @conditions.setter
    def conditions(self, conditions):
        """Sets the conditions of this IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus.

        Current service state of apiService.  # noqa: E501

        :param conditions: The conditions of this IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus.  # noqa: E501
        :type: list[IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceCondition]
        """

        self._conditions = conditions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
