# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from argo.models.io_k8s_apimachinery_pkg_apis_meta_v1_label_selector import IoK8sApimachineryPkgApisMetaV1LabelSelector  # noqa: F401,E501


class IoK8sApiAutoscalingV2beta2MetricIdentifier(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'selector': 'IoK8sApimachineryPkgApisMetaV1LabelSelector'
    }

    attribute_map = {
        'name': 'name',
        'selector': 'selector'
    }

    def __init__(self, name=None, selector=None):  # noqa: E501
        """IoK8sApiAutoscalingV2beta2MetricIdentifier - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._selector = None
        self.discriminator = None
        self.name = name
        if selector is not None:
            self.selector = selector

    @property
    def name(self):
        """Gets the name of this IoK8sApiAutoscalingV2beta2MetricIdentifier.  # noqa: E501

        name is the name of the given metric  # noqa: E501

        :return: The name of this IoK8sApiAutoscalingV2beta2MetricIdentifier.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this IoK8sApiAutoscalingV2beta2MetricIdentifier.

        name is the name of the given metric  # noqa: E501

        :param name: The name of this IoK8sApiAutoscalingV2beta2MetricIdentifier.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def selector(self):
        """Gets the selector of this IoK8sApiAutoscalingV2beta2MetricIdentifier.  # noqa: E501


        :return: The selector of this IoK8sApiAutoscalingV2beta2MetricIdentifier.  # noqa: E501
        :rtype: IoK8sApimachineryPkgApisMetaV1LabelSelector
        """
        return self._selector

    @selector.setter
    def selector(self, selector):
        """Sets the selector of this IoK8sApiAutoscalingV2beta2MetricIdentifier.


        :param selector: The selector of this IoK8sApiAutoscalingV2beta2MetricIdentifier.  # noqa: E501
        :type: IoK8sApimachineryPkgApisMetaV1LabelSelector
        """

        self._selector = selector

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoK8sApiAutoscalingV2beta2MetricIdentifier, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoK8sApiAutoscalingV2beta2MetricIdentifier):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
