# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from argo.models.io_k8s_apimachinery_pkg_apis_meta_v1_label_selector import IoK8sApimachineryPkgApisMetaV1LabelSelector  # noqa: F401,E501
from argo.models.io_k8s_apimachinery_pkg_util_intstr_int_or_string import IoK8sApimachineryPkgUtilIntstrIntOrString  # noqa: F401,E501


class IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'max_unavailable': 'IoK8sApimachineryPkgUtilIntstrIntOrString',
        'min_available': 'IoK8sApimachineryPkgUtilIntstrIntOrString',
        'selector': 'IoK8sApimachineryPkgApisMetaV1LabelSelector'
    }

    attribute_map = {
        'max_unavailable': 'maxUnavailable',
        'min_available': 'minAvailable',
        'selector': 'selector'
    }

    def __init__(self, max_unavailable=None, min_available=None, selector=None):  # noqa: E501
        """IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec - a model defined in Swagger"""  # noqa: E501
        self._max_unavailable = None
        self._min_available = None
        self._selector = None
        self.discriminator = None
        if max_unavailable is not None:
            self.max_unavailable = max_unavailable
        if min_available is not None:
            self.min_available = min_available
        if selector is not None:
            self.selector = selector

    @property
    def max_unavailable(self):
        """Gets the max_unavailable of this IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec.  # noqa: E501


        :return: The max_unavailable of this IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec.  # noqa: E501
        :rtype: IoK8sApimachineryPkgUtilIntstrIntOrString
        """
        return self._max_unavailable

    @max_unavailable.setter
    def max_unavailable(self, max_unavailable):
        """Sets the max_unavailable of this IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec.


        :param max_unavailable: The max_unavailable of this IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec.  # noqa: E501
        :type: IoK8sApimachineryPkgUtilIntstrIntOrString
        """

        self._max_unavailable = max_unavailable

    @property
    def min_available(self):
        """Gets the min_available of this IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec.  # noqa: E501


        :return: The min_available of this IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec.  # noqa: E501
        :rtype: IoK8sApimachineryPkgUtilIntstrIntOrString
        """
        return self._min_available

    @min_available.setter
    def min_available(self, min_available):
        """Sets the min_available of this IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec.


        :param min_available: The min_available of this IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec.  # noqa: E501
        :type: IoK8sApimachineryPkgUtilIntstrIntOrString
        """

        self._min_available = min_available

    @property
    def selector(self):
        """Gets the selector of this IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec.  # noqa: E501


        :return: The selector of this IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec.  # noqa: E501
        :rtype: IoK8sApimachineryPkgApisMetaV1LabelSelector
        """
        return self._selector

    @selector.setter
    def selector(self, selector):
        """Sets the selector of this IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec.


        :param selector: The selector of this IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec.  # noqa: E501
        :type: IoK8sApimachineryPkgApisMetaV1LabelSelector
        """

        self._selector = selector

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
